# Generated by Phase 2 model slimming - 2026-03-05
# Removes 30+ models, keeps only 4 AI-specific models
# Changes Comment: FK(Post/User) -> UUIDField (Spring cross-reference)

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_commentfilterrule_post_filteredcommentlog_and_more'),
    ]

    operations = [
        # ============================================================
        # Step 1: Remove FK constraints from Comment
        # (must be done before deleting Post/User tables)
        # ============================================================
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),

        # ============================================================
        # Step 2: Add UUID fields to Comment
        # ============================================================
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
            preserve_default=False,
        ),

        # ============================================================
        # Step 3: Remove models that depend on User/Artist first
        # ============================================================

        # FilteredCommentLog references Comment (keep) - no action needed
        # ChatMessage depends on StreamingEvent + User
        migrations.DeleteModel(name='ChatMessage'),
        # LiveHeart depends on StreamingEvent + User
        migrations.DeleteModel(name='LiveHeart'),
        # StreamingEvent depends on Artist
        migrations.DeleteModel(name='StreamingEvent'),

        # TicketReservation depends on User + CrawledConcert
        migrations.DeleteModel(name='TicketReservation'),
        # CrawledConcert (no FK deps)
        migrations.DeleteModel(name='CrawledConcert'),

        # SupportTicket depends on User
        migrations.DeleteModel(name='SupportTicket'),

        # Vote depends on User + VoteOption + Poll
        migrations.DeleteModel(name='Vote'),
        # VoteOption depends on Poll
        migrations.DeleteModel(name='VoteOption'),
        # Poll (no FK deps)
        migrations.DeleteModel(name='Poll'),

        # VotingPower depends on User
        migrations.DeleteModel(name='VotingPower'),
        # Point depends on User
        migrations.DeleteModel(name='Point'),
        # PointTransaction depends on User
        migrations.DeleteModel(name='PointTransaction'),
        # Membership depends on User
        migrations.DeleteModel(name='Membership'),
        # Notification depends on User
        migrations.DeleteModel(name='Notification'),
        # Media depends on User
        migrations.DeleteModel(name='Media'),
        # Like depends on User
        migrations.DeleteModel(name='Like'),
        # SavedPost depends on User
        migrations.DeleteModel(name='SavedPost'),
        # SearchHistory depends on User
        migrations.DeleteModel(name='SearchHistory'),
        # AuthToken depends on User
        migrations.DeleteModel(name='AuthToken'),
        # OAuthAccount depends on User
        migrations.DeleteModel(name='OAuthAccount'),
        # UserSettings depends on User
        migrations.DeleteModel(name='UserSettings'),
        # UserDailyMission depends on User
        migrations.DeleteModel(name='UserDailyMission'),
        # UserFavorite depends on User + Artist
        migrations.DeleteModel(name='UserFavorite'),
        # Post depends on User + Artist
        migrations.DeleteModel(name='Post'),

        # Now delete User and Artist (no more dependents)
        migrations.DeleteModel(name='User'),
        migrations.DeleteModel(name='Artist'),

        # Standalone models with no FK deps
        migrations.DeleteModel(name='CrawledChart'),
        migrations.DeleteModel(name='CrawledChartHistory'),
        migrations.DeleteModel(name='CrawledAd'),
        migrations.DeleteModel(name='FAQ'),
        migrations.DeleteModel(name='Notice'),
        migrations.DeleteModel(name='Reward'),
    ]
