# Generated by Django 4.2.9 on 2026-01-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlednews',
            name='origin_news',
            field=models.TextField(blank=True, null=True),
        ),
    ]
